### ISSUE TITLE
Documenting a simple Promise to Righto migration case

### ISSUE THREAD

**Issue by jwulf** [KoryNunn/righto#19]
Can we get something in the docs like this:

Here is how you make a Promise into a Righto:

Given this typical Promise pattern:

```
function writeFile(file) {
    return new Promise((resolve, reject) => {
        if (!file) {
             return reject('file cannot be falsy!');
        }
        fs.writeFile(file, (error, result) => {
            if (error) {
                reject(error);
            } else {
                resolve(result);
            }
        }
    }
}

writeFile('someFile')
    .then(result => console.log(result))
    .catch(error => console.log(error));
```

Here's how you do exactly the same thing with righto:

```
???
```

**Comment by KoryNunn** [comment]
Hmm, this sounds like something that would got in wiki pages. TBH, It's really hard for me to come up with scenarios moving from promises to righto, as I don't use promises.

One think I'd recommend, which is different to how you code with promises, is to not pass rightos' around too much, just use them when you need to handle async flow, and expose functionality as the usual error-back style.

The example you have above does not benefit from any form of async flow control, because there is only one operation happening, so I'd write it as such:

```
function writeFile(file, callback){
    if(!file){
        // This is probably a critical coding error. Throw.
        // Now you get a nice stack trace.
        throw new Error('file cannot be falsy!');
    }

    fs.writeFile('./path.ext', file, callback);
}
```
And then if I needed to use this in a flow:

```
function getImportantBit(file, callback){
    var match = file.match(/Hello world (\w+)/
    
    if(!match){
        return callback(new Error('No important bit in file'));
    }

    callback(null, match[1]);
}

function doSomeStuff(callback){
    var loadedFile = righto(fs.readFile, './readPath', 'utf8');
    var partOfFileIWantToWrite = righto(getImportantBit, loadedFile);
    var writtenImportantBit = righto(writeFile, partOfFileIWantToWrite);

    writtenImportantBit(callback);
}

doSomeStuff((error, result) => ... )
```

**Comment by KoryNunn** [comment]
@jwulf If you could share any scenarios you find where you're not sure how to migrate, I'll provide examples. It would be super handy!

**Comment by KoryNunn** [comment]
Here's a start: https://github.com/KoryNunn/righto/wiki/promise-migration-examples

**Comment by KoryNunn** [comment]
Closing as it's good enough for now.
